"""
CycloneGuard AI - Scenario Simulator Schemas (Phase 5)

Pydantic models for parametric cyclone "What-If" impact simulations:
- Wind Speed
- Rainfall
- Storm Surge
- Cyclone Track Offset
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class SimulationScenarioInput(BaseModel):
    """Scenario simulation control parameters."""
    wind_speed: float = Field(
        220.0,
        ge=90.0,
        le=260.0,
        description="Sustained wind speed in km/h (safe min: 90, max: 260)"
    )
    rainfall: float = Field(
        284.0,
        ge=100.0,
        le=500.0,
        description="Peak 24h rainfall in mm (safe min: 100, max: 500)"
    )
    storm_surge: float = Field(
        4.2,
        ge=0.0,
        le=5.0,
        description="Peak storm surge height in meters (safe min: 0.0, max: 5.0)"
    )
    track_offset_km: float = Field(
        0.0,
        ge=-50.0,
        le=50.0,
        description="Track offset in km (-50km West/Inland to +50km East/Offshore)"
    )
    scenario_name: Optional[str] = Field(
        None,
        description="User-assigned or auto-generated name for this scenario"
    )

class ImpactMetrics(BaseModel):
    """Aggregate quantitative disaster impact metrics."""
    population_exposed: int = Field(..., description="Total estimated population in affected impact zones")
    high_risk_population: int = Field(..., description="Population in high and critical risk zones")
    high_risk_zones_count: int = Field(..., description="Number of zones categorized as high or critical")
    critical_infrastructure_at_risk: int = Field(..., description="Total count of critical infrastructure assets at risk")
    roads_exposed: int = Field(..., description="Number of critical road corridors at risk")
    bridges_exposed: int = Field(..., description="Number of critical bridges at risk")
    hospitals_exposed: int = Field(..., description="Number of hospitals at risk")
    power_assets_exposed: int = Field(..., description="Number of power substations at risk")
    shelters_exposed: int = Field(..., description="Number of cyclone shelters at risk or exposed")

class MetricComparison(BaseModel):
    """Comparison between baseline and simulated scenario for a single metric."""
    baseline: float
    scenario: float
    delta: float
    percent_change: float

class SimulationDeltaMetrics(BaseModel):
    """Comparison deltas across all impact metrics."""
    population_exposed: MetricComparison
    high_risk_population: MetricComparison
    high_risk_zones_count: MetricComparison
    critical_infrastructure_at_risk: MetricComparison
    roads_exposed: MetricComparison
    bridges_exposed: MetricComparison
    hospitals_exposed: MetricComparison
    power_assets_exposed: MetricComparison
    shelters_exposed: MetricComparison

class TrackPoint(BaseModel):
    lat: float
    lng: float
    label: str
    category: int
    wind_speed_kmh: float

class ScenarioSimulationResponse(BaseModel):
    """Complete simulation evaluation response."""
    scenario_id: str
    scenario_name: str
    timestamp: str
    parameters: SimulationScenarioInput
    baseline_metrics: ImpactMetrics
    scenario_metrics: ImpactMetrics
    deltas: SimulationDeltaMetrics
    risk_zones: List[Dict[str, Any]]
    infrastructure_summary: Dict[str, Any]
    shifted_track: List[TrackPoint]
    baseline_track: List[TrackPoint]
    landfall_shift_km: float
    disclaimer: str = "SIMULATED SCENARIO — NOT AN OFFICIAL FORECAST"
    notice: str = "Decision-support simulation generated by CycloneGuard AI Risk Engine."
